In [5]:
import numpy as np
y = np.matrix([[0,1,2,3,4,5,6,7,8,9]])
y_matrix = y.reshape(-1)
y_matrix = np.eye(10)[y_matrix]
print(y_matrix)


[[1 2 3 4 5 6 7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(np.eye(10)[y_matrix]

[[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]]


In [7]:
import numpy as np
a = np.matrix([[1,2,3],[2,3,1],[2,1,3]])
y = np.array([1,2,3])
y_matrix = y.reshape(-1)
c = y_matrix*a
print(y*a)

[[11 11 14]]


In [9]:
print(c[1])

IndexError: index 1 is out of bounds for axis 0 with size 1

In [16]:
y = np.matrix([1,2,3,4,5,6,7,8,9,0])
ymat = y.reshape(-1)
b = np.eye(10)[ymat]
print(b)


IndexError: index 9 is out of bounds for axis 0 with size 9

In [26]:
import os
import numpy as np
from scipy.io import loadmat
data = loadmat(os.path.join('Data', 'ex4data1.mat'))
y = data['y'].ravel()
y_matrix = y.reshape(-1)
y[y==10] = 0
print(y_matrix)

[0 0 0 ... 9 9 9]


In [22]:
y_matrix = np.eye(10)[y_matrix]

In [23]:
print(y_matrix)

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [28]:
print(np.shape(y_matrix))

(5000,)


In [29]:
y_matrix[10]

0

In [30]:
y_matrix[17]

0

In [31]:
y_matrix[0]

0

In [32]:
y_matrix[1]

0

In [33]:
y_matrix[0][0]

IndexError: invalid index to scalar variable.

In [1]:
import numpy as np
y1 = np.matrix([[1,2,3],[4,5,6]])
y2 = np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(np.dot(y1,y2))

[[ 38  44  50  56]
 [ 83  98 113 128]]


In [1]:
import numpy as np
y1 = np.matrix([[1,2,3],[4,5,6]])
y2 = np.matrix([[1,2,3,4],[5,6,7,8]])
printnp.dot(y1,y2)

ValueError: shapes (2,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)